[build]
functions = "netlify/functions"
publish = "dist"
command = "npx vite build"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# SPA fallback - this is crucial for React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200